/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "cream": "#f5f4ed",
        "anthracite": "#1A1A1A",
        "on-tertiary-container": "#00314f",
        "primary-container": "#e5e2e1",
        "on-error-container": "#752121",
        "inverse-primary": "#ffffff",
        "error-container": "#fe8983",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#e5e2e1",
        "surface": "#fbf9f4",
        "tertiary-dim": "#005887",
        "background": "#fbf9f4",
        "surface-container": "#efeee6",
        "primary": "#1A1A1A",
        "on-surface-variant": "#5e6058",
        "on-secondary-container": "#4f5254",
        "secondary-fixed": "#e1e3e5",
        "on-tertiary": "#f6f9ff",
        "secondary": "#5d5f62",
        "secondary-container": "#e1e3e5",
        "surface-bright": "#fbf9f4",
        "surface-tint": "#1A1A1A",
        "inverse-surface": "#0e0e0c",
        "secondary-fixed-dim": "#d3d4d7",
        "tertiary": "#006499",
        "on-background": "#31332c",
        "surface-variant": "#e2e3d9",
        "error": "#9f403d",
        "on-primary": "#faf7f6",
        "surface-container-high": "#e8e9e0",
        "surface-container-low": "#f5f4ed",
        "primary-fixed-dim": "#d6d4d3",
        "on-primary-fixed-variant": "#5c5b5b",
        "on-surface": "#31332c",
        "surface-container-highest": "#e2e3d9",
        "on-secondary": "#f7f9fb",
        "tertiary-container": "#62b5f7",
        "outline": "#797c73",
        "surface-dim": "#d9dbcf",
        "on-tertiary-fixed": "#001627",
        "inverse-on-surface": "#9e9d99",
        "error-dim": "#4e0309",
        "on-secondary-fixed": "#3d4042",
        "secondary-dim": "#515356",
        "outline-variant": "#b1b3a9",
        "tertiary-fixed-dim": "#52a7e8",
        "on-tertiary-fixed-variant": "#003a5c",
        "on-error": "#fff7f6",
        "on-primary-container": "#525151",
        "on-primary-fixed": "#403f3f",
        "on-secondary-fixed-variant": "#595c5e",
        "tertiary-fixed": "#62b5f7",
        "primary-dim": "#535252"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "9999px",
        "organic": "30% 70% 70% 30% / 30% 30% 70% 70%"
      },
    },
  },
  plugins: [],
}
